### ISSUE TITLE
Adultempire issue 415 HTTP return code

### ISSUE THREAD

**Issue by ShadowWalker99** [porn-vault/plugins#178]
Sometimes when loading the *bh* image, the server returns a 415 error which makes the plugin crash.

```
2021-03-14T09:14:57.106Z [vault] info: Downloading https://imgs1cdn.adultempire.com/products/30/3068930bh.jpg to library\images\im_km8xzavmH2FqwyzN.jpg...
Fetching |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0/0 MB | Speed: N/AkB/s2021-03-14T09:14:57.556Z [vault] error: Plugin error: Request failed with status code 415
2021-03-14T09:14:57.557Z [vault] debug: Error: Request failed with status code 415
    at createError (C:\snapshot\porn-vault\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\snapshot\porn-vault\node_modules\axios\lib\core\settle.js:17:12)
    at RedirectableRequest.handleResponse (C:\snapshot\porn-vault\node_modules\axios\lib\adapters\http.js:231:9)
    at RedirectableRequest.emit (events.js:315:20)
    at RedirectableRequest.EventEmitter.emit (domain.js:485:12)
    at RedirectableRequest._processResponse (C:\snapshot\porn-vault\node_modules\follow-redirects\index.js:380:10)
    at ClientRequest.<anonymous> (C:\snapshot\porn-vault\node_modules\follow-redirects\index.js:56:10)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
2021-03-14T09:14:57.557Z [vault] error: Ran 1 plugins with 1 errors.
```

**Comment by boi123212321** [comment]
This happens with a lot of Private movies especially because they sometimes just don't have a back cover
